# **Problem - 1: Array Creation:**
**Complete the following Tasks:**

**1. Initialize an empty array with size 2X2.**

In [ ]:
import numpy as np

# Create an empty 2x2 array
arr = np.empty((2, 2))

print(arr)


[[4.63786331e-315 0.00000000e+000]
 [6.55936091e-085 5.59121966e+252]]


**2. Initialize an all one array with size 4X2.**


In [ ]:
import numpy as np

# Initialize all ones 4x2 array
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}**

In [ ]:
import numpy as np

# Create 3x3 array filled with 42
filled_array = np.full((3, 3), 42)
print(filled_array)

# With custom dtype (integers)
filled_int = np.full((2, 4), 7, dtype=int)
print("\nInteger version:\n", filled_int)


[[42 42 42]
 [42 42 42]
 [42 42 42]]

Integer version:
 [[7 7 7 7]
 [7 7 7 7]]


**4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}**


In [ ]:
import numpy as np

# Given array
original = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

# Zeros array with same shape and type
zeros_array = np.zeros_like(original)
print("Original array:\n", original)
print("Zeros array:\n", zeros_array)


Original array:
 [[1. 2. 3.]
 [4. 5. 6.]]
Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


**5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}**


In [ ]:
import numpy as np

# Given array
original = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)

# Ones array with same shape and type
ones_array = np.ones_like(original)
print("Original array:\n", original)
print("Ones array:\n", ones_array)


Original array:
 [[1. 2. 3.]
 [4. 5. 6.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]


**6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}**


In [ ]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert to NumPy array
numpy_array = np.array(new_list)
print("Original list:", new_list)
print("NumPy array:", numpy_array)
print("Type:", type(numpy_array))


Original list: [1, 2, 3, 4]
NumPy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>


# **Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
**Complete the following tasks:**

**1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.**

In [ ]:
import numpy as np

# Create array from 10 to 49
range_array = np.arange(10, 50)
print(range_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}**

In [ ]:
import numpy as np

# Create 1D array 0-8, then reshape to 3x3
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


**3. Create a 3X3 identity matrix.{Hint:np.eye()}**


In [ ]:
import numpy as np

# Create 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}**


In [ ]:
import numpy as np

# Create random array of size 30 (values between 0 and 1)
random_array = np.random.random(30)

# Calculate mean
array_mean = random_array.mean()

print("Random array:", random_array)
print("Mean:", array_mean)


Random array: [0.53499572 0.29158228 0.21764003 0.30618035 0.92132732 0.02248443
 0.43994218 0.9851602  0.47655407 0.8369137  0.17328159 0.31905543
 0.72477631 0.10828144 0.66602736 0.2411229  0.43831775 0.34335586
 0.403993   0.85722208 0.77264196 0.45130788 0.60827486 0.70649069
 0.72697824 0.83640881 0.15242657 0.37135017 0.39671207 0.661129  ]
Mean: 0.49973114033183363


**5. Create a 10X10 array with random values and find the minimum and maximum values.**

In [ ]:
import numpy as np

# Create 10x10 random array
random_10x10 = np.random.random((10, 10))

# Find min and max values
min_value = random_10x10.min()
max_value = random_10x10.max()

print("10x10 Random Array (first 5x5 shown):\n", random_10x10[:5, :5])
print("Minimum value:", min_value)
print("Maximum value:", max_value)


10x10 Random Array (first 5x5 shown):
 [[0.67884074 0.79553737 0.56459956 0.46591312 0.84050585]
 [0.46287146 0.53961722 0.93366622 0.58886327 0.63866104]
 [0.10771988 0.08249779 0.52293849 0.99883871 0.97324002]
 [0.74900111 0.19189795 0.49986365 0.15071368 0.52450779]
 [0.02403415 0.05062555 0.32819211 0.07960987 0.80451064]]
Minimum value: 0.010537880718701986
Maximum value: 0.998838711158167


**6. Create a zero array of size 10 and replace 5th element with 1.**

In [ ]:
import numpy as np

# Create zero array of size 10
zero_array = np.zeros(10)

# Replace 5th element (index 4) with 1
zero_array[4] = 1

print("Modified array:", zero_array)


Modified array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7. Reverse an array arr = [1,2,0,0,4,0].**

In [ ]:
import numpy as np

# Original array
arr = np.array([1, 2, 0, 0, 4, 0])

# Method 1: Slicing (most common)
reversed_arr = arr[::-1]
print("Original:", arr)
print("Reversed:", reversed_arr)


Original: [1 2 0 0 4 0]
Reversed: [0 4 0 0 2 1]


**8. Create a 2d array with 1 on border and 0 inside.**

In [ ]:
import numpy as np

# Create 5x5 array of ones
array = np.ones((5, 5))

# Set inner elements (excluding border) to 0
array[1:-1, 1:-1] = 0

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**9. Create a 8X8 matrix and fill it with a checkerboard pattern.**


In [ ]:
import numpy as np

# Create 8x8 zeros array
checkerboard = np.zeros((8, 8), dtype=int)

# Fill checkerboard pattern
checkerboard[1::2, ::2] = 1    # Odd rows, even columns
checkerboard[::2, 1::2] = 1    # Even rows, odd columns

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **Problem - 3: Array Operations:**
**For the following arrays:**

**x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);**

**v = np.array([9,10]) and w = np.array([11,12]);**

**Complete all the task using numpy:**

**1. Add the two array.**

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Method 1: + operator (element-wise addition)
result_add = x + y
print("x + y:\n", result_add)

# Method 2: np.add() function
result_np = np.add(x, y)
print("\nnp.add(x, y):\n", result_np)


x + y:
 [[ 6  8]
 [10 13]]

np.add(x, y):
 [[ 6  8]
 [10 13]]


**2. Subtract the two array.**

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Method 1: - operator (element-wise subtraction)
result_sub = x - y
print("x - y:\n", result_sub)

# Method 2: np.subtract() function
result_np = np.subtract(x, y)
print("\nnp.subtract(x, y):\n", result_np)


x - y:
 [[-4 -4]
 [-4 -3]]

np.subtract(x, y):
 [[-4 -4]
 [-4 -3]]


**3. Multiply the array with any integers of your choice.**


In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Multiply each array by chosen integers
x_times_3 = x * 3
y_times_2 = y * 2

print("Original x:\n", x)
print("x * 3:\n", x_times_3)
print("\nOriginal y:\n", y)
print("y * 2:\n", y_times_2)


Original x:
 [[1 2]
 [3 5]]
x * 3:
 [[ 3  6]
 [ 9 15]]

Original y:
 [[5 6]
 [7 8]]
y * 2:
 [[10 12]
 [14 16]]


**4. Find the square of each element of the array.**

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Method 1: **2 operator (element-wise square)
x_squared = x ** 2
y_squared = y ** 2

print("x squared:\n", x_squared)
print("y squared:\n", y_squared)

# Method 2: np.square() function
x_sq_np = np.square(x)
print("\nnp.square(x):\n", x_sq_np)


x squared:
 [[ 1  4]
 [ 9 25]]
y squared:
 [[25 36]
 [49 64]]

np.square(x):
 [[ 1  4]
 [ 9 25]]


**5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.**

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. v · w (1D vector dot product → scalar)
v_dot_w = np.dot(v, w)
print("v · w =", v_dot_w)

# 2. x · v (2D matrix × 1D vector → 2×1 vector)
x_dot_v = np.dot(x, v)
print("x · v =", x_dot_v)

# 3. x · y (2D matrix × 2D matrix → 2×2 matrix)
x_dot_y = np.dot(x, y)
print("x · y =\n", x_dot_y)


v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]


**6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.**


In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Concatenate x and y along rows (vertical)
xy_rows = np.concatenate((x, y), axis=0)
print("x and y along rows:\n", xy_rows)

# 2. Concatenate v and w along columns (horizontal)
vw_cols = np.concatenate((v, w), axis=0).reshape(1, -1)
print("\nv and w along columns:\n", vw_cols)


x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

v and w along columns:
 [[ 9 10 11 12]]


**7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?**

In [ ]:
v_2d = v.reshape(1, -1)  # Shape: (1, 2)
result = np.concatenate((x, v_2d), axis=0)
print(result)
# [[1 2]
#  [3 5]
#  [9 10]]


[[ 1  2]
 [ 3  5]
 [ 9 10]]


**ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)**

# **Problem - 4: Matrix Operations:**
**• For the following arrays:**

**A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);**

**Prove following with Numpy:**

**1. Prove A.A−1 = I.**

In [ ]:
import numpy as np

# Given matrix A
A = np.array([[3, 4], [7, 8]])

# Calculate inverse A⁻¹
A_inv = np.linalg.inv(A)

# Compute A · A⁻¹
result = np.dot(A, A_inv)

# Identity matrix I (2x2)
I = np.eye(2)

print("A:\n", A)
print("A⁻¹:\n", A_inv)
print("A · A⁻¹:\n", result)
print("Is equal to I?", np.allclose(result, I))


A:
 [[3 4]
 [7 8]]
A⁻¹:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A · A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is equal to I? True


**2. Prove AB ̸= BA.**

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A:\n", A)
print("B:\n", B)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))


A:
 [[3 4]
 [7 8]]
B:
 [[5 3]
 [2 1]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False


**3. Prove (AB) T = BTAT.**



In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute both sides
AB = np.dot(A, B)
AB_transpose = np.transpose(AB)

BT_AT = np.dot(np.transpose(B), np.transpose(A))
# or: np.transpose(A) @ np.transpose(B)

print("AB:\n", AB)
print("(AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("Equal?", np.array_equal(AB_transpose, BT_AT))


AB:
 [[23 13]
 [51 29]]
(AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Equal? True


**• Solve the following system of Linear equation using Inverse Methods.**

**2x − 3y + z = −1**

**x − y + 2z = −3**

**3x + y − z = 9**

**{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}**


In [ ]:
import numpy as np

# Coefficient matrix A and constant vector B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Method 1: X = A⁻¹B (using inverse)
A_inv = np.linalg.inv(A)
X_inverse = np.dot(A_inv, B)

print("Solution using A⁻¹B:")
print("x =", X_inverse[0])
print("y =", X_inverse[1])
print("z =", X_inverse[2])
print("X =", X_inverse)


Solution using A⁻¹B:
x = 2.0
y = 1.0
z = -2.0
X = [ 2.  1. -2.]


**• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}**


In [ ]:
import numpy as np

# Matrix form: AX = B
A = np.array([[2, -3,  1],
              [1, -1,  2],
              [3,  1, -1]])

B = np.array([-1, -3, 9])

# Step 1: Compute inverse using np.linalg.inv()
A_inv = np.linalg.inv(A)
print("A⁻¹ =\n", A_inv)

# Step 2: Solve X = A⁻¹B
X = np.dot(A_inv, B)
print("\nSolution X =", X)
print("x =", X[0], "y =", X[1], "z =", X[2])


A⁻¹ =
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution X = [ 2.  1. -2.]
x = 2.0 y = 1.0 z = -2.0


# **10.2 Experiment: How Fast is Numpy?**

**In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays.**

**Follow the instructions:**

**1. Element-wise Addition:**

**• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.**




In [ ]:
import time

# Create two lists of 1,000,000 elements
size = 1000000
list1 = list(range(size))
list2 = list(range(size, size + size))

# Measure time for element-wise addition using list comprehension
start_time = time.time()

# Element-wise addition: [a + b for each pair]
result_list = [list1[i] + list2[i] for i in range(size)]

list_time = time.time() - start_time

print(f"Size: {size:,} elements")
print(f"Python Lists - Element-wise addition time: {list_time:.4f} seconds")
print(f"Result preview: {result_list[:5]}...")  # First 5 elements

Size: 1,000,000 elements
Python Lists - Element-wise addition time: 0.2288 seconds
Result preview: [1000000, 1000002, 1000004, 1000006, 1000008]...


**• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.**

In [ ]:
import numpy as np
import time

# Create two NumPy arrays of 1,000,000 elements
size = 1000000
array1 = np.arange(size)
array2 = np.arange(size, size + size)

# Measure time for element-wise addition
start_time = time.time()

# Single operation: vectorized element-wise addition
result_array = array1 + array2

numpy_time = time.time() - start_time

print(f"Size: {size:,} elements")
print(f"NumPy Arrays - Element-wise addition time: {numpy_time:.4f} seconds")
print(f"Result preview: {result_array[:5]}...")  # First 5 elements


Size: 1,000,000 elements
NumPy Arrays - Element-wise addition time: 0.0088 seconds
Result preview: [1000000 1000002 1000004 1000006 1000008]...


**2. Element-wise Multiplication**

**• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.**

In [ ]:
import time

# Create two lists of 1,000,000 elements
size = 1000000
list1 = list(range(size))
list2 = list(range(size, size + size))

# Measure time for element-wise multiplication using list comprehension
start_time = time.time()

# Element-wise multiplication: [a * b for each pair]
result_list = [list1[i] * list2[i] for i in range(size)]

list_time = time.time() - start_time

print(f"Size: {size:,} elements")
print(f"Python Lists - Element-wise multiplication time: {list_time:.4f} seconds")
print(f"Result preview: {result_list[:5]}...")  # First 5 elements


Size: 1,000,000 elements
Python Lists - Element-wise multiplication time: 0.1382 seconds
Result preview: [0, 1000001, 2000004, 3000009, 4000016]...


**• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.**


In [ ]:
import numpy as np
import time

# Create two NumPy arrays of 1,000,000 elements
size = 1000000
array1 = np.arange(size)
array2 = np.arange(size, size + size)

# Measure time for element-wise multiplication
start_time = time.time()

# Single operation: vectorized element-wise multiplication
result_array = array1 * array2

numpy_time = time.time() - start_time

print(f"Size: {size:,} elements")
print(f"NumPy Arrays - Element-wise multiplication time: {numpy_time:.4f} seconds")
print(f"Result preview: {result_array[:5]}...")  # First 5 elements


Size: 1,000,000 elements
NumPy Arrays - Element-wise multiplication time: 0.0048 seconds
Result preview: [      0 1000001 2000004 3000009 4000016]...


**3. Dot Product**

**• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.**


In [ ]:
import time

# Create two lists of 1,000,000 elements
size = 1000000
list1 = list(range(size))
list2 = list(range(size, size + size))

# Measure time for dot product
start_time = time.time()

# Dot product: sum(list1[i] * list2[i] for all i)
dot_product = sum(list1[i] * list2[i] for i in range(size))

list_time = time.time() - start_time

print(f"Size: {size:,} elements")
print(f"Python Lists - Dot product time: {list_time:.4f} seconds")
print(f"Dot product result: {dot_product}")


Size: 1,000,000 elements
Python Lists - Dot product time: 0.2314 seconds
Dot product result: 833332333333500000


**• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.**


In [ ]:
import numpy as np
import time

# Create two NumPy arrays of 1,000,000 elements
size = 1000000
array1 = np.arange(size)
array2 = np.arange(size, size + size)

# Measure time for dot product
start_time = time.time()

# Single operation: vectorized dot product
dot_product = np.dot(array1, array2)

numpy_time = time.time() - start_time

print(f"Size: {size:,} elements")
print(f"NumPy Arrays - Dot product time: {numpy_time:.4f} seconds")
print(f"Dot product result: {dot_product}")


Size: 1,000,000 elements
NumPy Arrays - Dot product time: 0.0023 seconds
Dot product result: 833332333333500000


**4. Matrix Multiplication**

**• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.**


In [ ]:
import time
import random

# Create two 1000x1000 matrices
n = 1000
matrix1 = [[random.randint(0, 10) for _ in range(n)] for _ in range(n)]
matrix2 = [[random.randint(0, 10) for _ in range(n)] for _ in range(n)]

# Measure time for matrix multiplication
start_time = time.time()

# Triple nested loop matrix multiplication: C[i][j] = Σ(A[i][k] * B[k][j])
result = [[0 for _ in range(n)] for _ in range(n)]
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

python_time = time.time() - start_time

print(f"Matrix size: {n}×{n} = {n*n:,} elements")
print(f"Python Lists - Matrix multiplication time: {python_time:.2f} seconds")
print(f"Result preview (top-left 3×3):\n{result[:3][:3]}")


Matrix size: 1000×1000 = 1,000,000 elements
Python Lists - Matrix multiplication time: 323.69 seconds
Result preview (top-left 3×3):
[[25077, 24086, 24470, 24314, 23896, 24697, 24775, 23768, 24878, 25239, 23528, 24377, 24642, 24969, 24867, 24399, 24180, 24689, 24643, 24329, 25341, 23866, 23014, 23618, 24440, 23818, 24474, 24792, 24074, 22851, 23998, 24362, 24875, 25497, 23792, 24188, 24488, 24306, 23991, 24390, 24303, 25558, 23887, 24579, 24784, 24116, 24441, 22598, 24712, 25044, 24246, 24079, 23548, 24277, 23563, 24106, 23497, 25495, 24093, 25217, 23459, 24138, 24155, 23770, 24889, 24365, 24001, 23036, 24860, 24801, 24516, 23741, 24022, 23580, 24399, 24784, 23854, 23919, 24186, 23825, 24366, 23977, 24142, 24684, 24254, 23514, 24918, 24864, 23413, 24536, 24865, 25150, 23723, 24526, 23969, 24068, 23893, 23820, 24289, 23603, 23553, 25216, 23842, 24293, 24650, 24071, 24131, 24343, 23222, 23934, 23820, 24299, 23333, 24095, 24591, 23631, 25059, 24916, 24077, 23439, 22915, 24643, 23441, 2365

**• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.**

In [ ]:
import numpy as np
import time

# Create two 1000x1000 random matrices
n = 1000
matrix1 = np.random.rand(n, n)
matrix2 = np.random.rand(n, n)

# Measure time for matrix multiplication
start_time = time.time()

# Single operation: optimized BLAS matrix multiplication
result = np.dot(matrix1, matrix2)
# Alternative: result = matrix1 @ matrix2

numpy_time = time.time() - start_time

print(f"Matrix size: {n}×{n} = {n*n:,} elements")
print(f"NumPy Arrays - Matrix multiplication time: {numpy_time:.2f} seconds")
print(f"Result shape: {result.shape}")
print(f"Result preview (top-left 3×3):\n{result[:3, :3]}")


Matrix size: 1000×1000 = 1,000,000 elements
NumPy Arrays - Matrix multiplication time: 0.10 seconds
Result shape: (1000, 1000)
Result preview (top-left 3×3):
[[245.87104398 257.06431537 257.71179111]
 [251.64110996 251.1049564  252.10513426]
 [253.52314838 257.4078746  260.29192885]]
